name: turf_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  dartclub_lint: ^0.2.1
  test: ^1.6.0
  json_serializable: ^3.4.1
  build_runner: ^1.0.0
